package com.epam.final_task.controller.command;

public enum CommandTypeEnum {

    RESERVATION,
    LOGIN,
    LOGOUT,
    ERROR,
    REGISTRATION,
    LANGUAGE,
    USERS,
    OFFERS,
    ADD_ROOM_SAVE,
    EDIT_ROOM_FORM,
    EDIT_ROOM_SAVE,
    TAKE_ROOM,
    PROFILE,
    RETURN_THE_ROOM,
    EDIT_PROFILE_FORM,
    EDIT_PROFILE_SAVE,
    HISTORY,
    CHANGE_PASSWORD_SAVE,
    EDIT_USER,
    EDIT_PASSWORD,
    ADD_ROOM_FORM,
    PAY_ROOM,
    ORDERS,
    ALLOW_ORDER,
    REPLENISH_BALANCE,
    TARIFFS,
    ADD_TARIFF_FORM,
    ADD_TARIFF_SAVE,
    EDIT_TARIFF_FORM,
    EDIT_TARIFF_SAVE,
    ROOM,
    USER_HISTORY

}
